owner: galaxyp
name: fasta_merge_files_and_filter_unique_sequences
categories:
  - Fasta Manipulation	
description: Concatenate FASTA database files together.
long_description: |
  Concatenate FASTA database files together.
  Only first appearence of each unique sequence will appear in output.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/master/tools/fasta_merge_files_and_filter_unique_sequences
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp/
