categories: !!python/tuple [Tool Dependency Packages]
description: !!python/unicode 'Tool dependencies for SearchGUI 2.8'
homepage_url: !!python/unicode 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_searchgui_2_8'
name: !!python/unicode 'package_searchgui_2_8'
owner: !!python/unicode 'galaxyp'
