categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that installs DIA-Umpire version 2.1 
long_description: |
  DIA-Umpire is an open source Java program for computational analysis of data independent acquisition (DIA) mass spectrometry-based proteomics data. It enables untargeted peptide and protein identification and quantitation using DIA data, and also incorporates targeted extraction to reduce the number of cases of missing quantitation. 
  https://github.com/Nesvilab/DIA-Umpire
name: package_dia_umpire_2_1
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_dia_umpire_2_1
homepage_url: https://github.com/Nesvilab/DIA-Umpire
type: tool_dependency_definition
