# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/idpqonvert
categories:
- Proteomics
owner: chambm
name: idpqonvert
description: Bumbershoot IDPicker idpQonvert - creates idpDB files from pepXML and mzIdentML files