# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/idpqonvert
categories:
- Proteomics
owner: galaxyp
name: idpqonvert
description: Bumbershoot IDPicker idpQonvert
homepage_url: http://proteowizard.sourceforge.net/
long_description: |
  Q-value + convert = qonvert
  idpQonvert qonverts raw pepXML and mzIdentML files to IDPicker idpDB files.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/bumbershoot/idpqonvert
