categories:
- Proteomics
description: Perform 3 frame translation of BED file augmented with a sequence column
long_description: |
  This tool takes an extended (12 column) BED input file that has been processed
  by the Galaxy tool "Extract Genomic DNA" to add a 13th column with the transcript sequence.
  It generates a peptide fasta file with the 3-frame translations of the spliced sequence 
  defined by each entry in the input BED file.
  It can also generate a bed file that defines the mapping of the translations to the 
  reference genome. The tool "Map peptides to a bed file" can use this output to map 
  peptides iidentified from a Proteomics search back to the reference genome.

Typical workflow:  tophat splice_junctions.bed into Extract Genomic DNA into translate_bed_sequences
name: translate_bed_sequences
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/translate_bed_sequences
type: unrestricted
