owner: jorritb
name: package_kronik_2_02
categories:
- Tool Dependency Packages
- Proteomics
description: Krönik 2.02
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_kronik_2_02
type: tool_dependency_definition
