# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/myrimatch
categories:
- Proteomics
owner: chambm
name: myrimatch
description: Bumbershoot MyriMatch - a shotgun proteomics search engine.