# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/myrimatch
categories:
- Proteomics
owner: galaxyp
name: myrimatch
description: Bumbershoot MyriMatch
homepage_url: http://proteowizard.sourceforge.net/
long_description: |
  MyriMatch is a shotgun proteomics search engine for tandem mass spectra.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/bumbershoot/myrimatch
