# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/idpassemble
categories:
- Proteomics
owner: galaxyp
name: idpassemble
description: Bumbershoot IDPicker idpAssemble
long_description: |
idpAssemble merges multiple idpDB files into a single idpDB. It can also filter the result at PSM/spectrum/peptide/protein/gene levels.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/bumbershoot/idpassemble