categories:
- Tool Dependency Packages
- Proteomics
name: package_xerces_c_3_1_1
description: Contains Xerces-C tool dependency definition that downloads and builds Xerces-C
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/packages/package_xerces_c_3_1_1/
type: tool_dependency_definition
owner: galaxyp
