owner: galaxyp
name: mz_to_sqlite
categories:
- Proteomics
description: PeptideShaker and SearchGUI
long_description: |
  Extract proteomics files: mzIdentML, mzML, MGF, fsata into a SQLite DB
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/mz_to_sqlite
type: unrestricted
