# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/pepxml_to_xls
owner: galaxyp
name: pepxml_to_xls
categories:
- Proteomics
description: Convert PepXML to Tabular
long_description: |
  This program will convert PepXML files to Tabular
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pepxml_to_xls
type: unrestricted
