categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads the Bumbershoot tools.
long_description: |
  Bumbershoot

  https://sourceforge.net/p/proteowizard/code/HEAD/tree/trunk/pwiz/pwiz_tools/Bumbershoot/
name: package_bumbershoot_3_0_8789
owner: chambm
type: tool_dependency_definition
