owner: galaxyp
name: probamconvert
categories:
- Proteomics
description: proBAMconvert
long_description: |
  proBAMconvert reads common peptide identification files and attempts to extract 
  all relevant attributes from the files, including comments and enzyme information, 
  and converts these attributes to comply with proBAM/proBED.

  https://github.com/Biobix/proBAMconvert
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/probamconvert
homepage_url: https://github.com/Biobix/proBAMconvert
type: unrestricted
