owner: galaxyp
name: msgfplus
categories:
- Proteomics
description: MSGF+
long_description: |
  Identifies peptides in tandem mass spectra using the MSGF+ search engine.

  http://proteomics.ucsd.edu/software-tools/ms-gf/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msgfplus
type: unrestricted
