owner: galaxyp
name: trans_proteomic_pipeline
categories:
- Proteomics
description: TPP Trans Proteomic Pipeline tools
long_description: |
  The Trans-Proteomic Pipeline (TPP) includes all of the steps of the ISB MS/MS analysis pipeline, after the database search.
  These TPP Galaxy tools are designed to work with DIA-Umpire

  http://www.proteomecenter.org/software.php

remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/trans_proteomic_pipeline
type: unrestricted
