categories: !!python/tuple [Tool Dependency Packages,Proteomics]
description: !!python/unicode 'Tool dependencies for PeptideShaker 0.38'
homepage_url: !!python/unicode 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_peptideshaker_0_38'
name: !!python/unicode 'package_peptideshaker_0_38'
owner: !!python/unicode 'iracooke'
