owner: galaxyp
name: hardklor
categories:
- Proteomics
description: Hardklör
long_description: |
  Identifies peptide or protein-like features in mass spectra, deconvolves overlapping ion signals, and can be used on a variety of input formats.

  https://proteome.gs.washington.edu/software/hardklor/

remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/hardklor
type: unrestricted
