# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/spectrast2tsv
owner: galaxyp
name: spectrast2tsv
categories:
- Proteomics
description: Filter from spectraST files to swath input files
long_description: |
  The algorithm can take targeted proteomics data, learn a linear separation
  between true signal and the noise signal and then compute a q-value (false discovery rate) to achieve experiment-wide cutoffs. 

  https://github.com/uweschmitt/pyprophet
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/spectrast2tsv
type: unrestricted
