owner: galaxyp
name: package_percolator_2_10
categories:
- Tool Dependency Packages
description: Percolator 2.10
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_percolator_2_10
type: unrestricted
