categories:
- Tool Dependency Packages
- Proteomics
name: package_percolator_2_10
description: Contains percolator tool dependency definition that downloads and builds percolator and its converters.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/packages/package_percolator_2_10/
type: tool_dependency_definition
owner: jorritb
