# repository published to https://testtoolshed.g2.bx.psu.edu/repos/galaxyp/idpquery
categories:
- Proteomics
owner: galaxyp
name: idpquery
description: Bumbershoot IDPicker idpQuery
long_description: |
  idpQuery creates customizable text reports from idpDB files.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/bumbershoot/idpquery