categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.3.2 of the msproteomicstools.
long_description: |
  msproteomicstools - python module for MS-based proteomics

  https://github.com/msproteomicstools/msproteomicstools
name: package_python_2_7_msproteomicstools_0_3_2
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_python_2_7_msproteomicstools_0_3_2
type: tool_dependency_definition
