categories:
- Tool Dependency Packages
- Proteomics
name: package_xsd_4_0_0_dep
description: Contains XSD tool dependency definition that downloads and builds XSD
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/packages/package_xsd_4_0_0_dep/
type: tool_dependency_definition
owner: galaxyp
