owner: galaxyp
name: percolator
categories:
- Proteomics
description: Percolator
long_description: |
  Uses a semi-supervised machine learning to discriminate correct from incorrect peptide-spectrum matches, and calculates accurate statistics such as q-value (FDR) and posterior error probabilities. 

  http://per-colator.com/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/percolator
type: unrestricted
