categories:
- Proteomics
description: Generate Novel Splice Junction Search DBs from RNAseq 
long_description: |
  Workflows generate a protein fasta and a bed file for novel 
  splice junctions identified from RNAseq data

Typical workflow:  tophat splice_junctions.bed into Extract Genomic DNA into translate_bed_sequences
name: proteogenomics_splice_junc_search_db
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/workflows/proteogenomics_splice_junc_search_db
type: unrestricted
