categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that installs DIA-Umpire version 2.0 
long_description: |
  DIA-Umpire is an open source Java program for computational analysis of data independent acquisition (DIA) mass spectrometry-based proteomics data. It enables untargeted peptide and protein identification and quantitation using DIA data, and also incorporates targeted extraction to reduce the number of cases of missing quantitation. 
  http://diaumpire.sourceforge.net/
name: package_dia_umpire_2_0
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_dia_umpire_2_0
homepage_url: http://diaumpire.sourceforge.net/
type: tool_dependency_definition
