categories:
- Proteomics
description: Contains tools for SWATH-MS analysis
long_description: |
  Various tools to analyse SWATH-MS data.
name: suite_swath_analysis
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/suites/suite_swath_analysis
type: repository_suite_definition
