owner: galaxyp
name: feature_alignment
categories:
- Proteomics
description: Feature Alignment of peakgroups below a FDR
long_description: |
  This program will select all peakgroups below the FDR cutoff in all files and try to align them to each other.
  If only one file is given, it will act as peakgroup selector (best by m_score)
  and will apply the provided FDR cutoff.

  https://github.com/msproteomicstools/msproteomicstools
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/feature_alignment
type: unrestricted
