owner: galaxyp
name: package_searchgui_2_1
categories:
- Tool Dependency Packages
description: PeptideShaker and SearchGUI 1.1
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_searchgui_2_1
type: unrestricted
