categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.13.2 of pyprophet.
long_description: |
  Python reimplementation of mProphet algorithm.

  https://github.com/uweschmitt/pyprophet
name: package_python_2_7_pyprophet_0_13_2
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_python_2_7_pyprophet_0_13_2
type: tool_dependency_definition
