categories: !!python/tuple [Tool Dependency Packages]
description: !!python/unicode 'Tool dependencies for SearchGUI 1.28'
homepage_url: !!python/unicode 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_searchgui_1_28'
name: !!python/unicode 'package_searchgui_1_28'
owner: !!python/unicode 'iracooke'
