categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads the Bumbershoot tools.
long_description: |
  MSGF+

  http://proteomics.ucsd.edu/software-tools/ms-gf/
name: package_msgfplus_v10089
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/packages/package_msgfplus_v10089/
owner: galaxyp
type: tool_dependency_definition
