categories: !!python/tuple [Tool Dependency Packages]
description: !!python/unicode 'Tool dependencies for PeptideShaker 1.11'
homepage_url: !!python/unicode 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_peptideshaker_1_11'
name: !!python/unicode 'package_peptideshaker_1_11'
owner: !!python/unicode 'galaxyp'
