categories:
- Proteomics
description: ASMS 2016  Tutorial Workflows
long_description: |
  Workflow for PeptideShaker PSM REPORT to NOVEL peptides

Typical workflow:  
name: asms_tutorial_2016
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/workflows/asms_tutorial_2016
type: unrestricted
