name: openms
owner: galaxyp
description: OpenMS Suite for LC/MS data management and analyses
homepage_url: https://www.openms.de/
long_description: |
  OpenMS is an open-source software C++ library for LC/MS data management and analyses. It offers an infrastructure for the rapid development of mass spectrometry related software.

  https://www.openms.de/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/openms
type: unrestricted
categories:
- Proteomics