# repository published to https://testtoolshed.g2.bx.psu.edu/repos/galaxyp/idpquery
categories:
- Proteomics
owner: chambm
name: idpquery
description: Bumbershoot IDPicker idpQuery - creates reports from idpDB files.