# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/decoyfasta
owner: galaxyp
name: decoyfasta
categories:
 - Proteomics
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/decoyfasta
description: Galaxy tool wrapper for the transproteomic pipeline decoyFASTA tool.
type: unrestricted
