categories:
- Proteomics
description: Download UniProt proteome in XML format
long_description: |
  Download UniProt proteome in XML format.  
  The Morpheus proteomics search engine uses the uniprotxml format.

name: uniprotxml_downloader
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/uniprotxml_downloader
type: unrestricted

