categories:
- Proteomics
description: Contains the Bumbershoot tools for analysis of shotgun proteomics data.
long_description: |
  Provides a search engine (MyriMatch), confidence assessment (idpQonvert), protein assembly (idpAssemble), and a query engine for producing text reports (idpQuery).
name: suite_bumbershoot
owner: galaxyp
type: repository_suite_definition
