categories: !!python/tuple [Tool Dependency Packages]
description: !!python/unicode 'Tool dependencies for PeptideShaker 0.39'
homepage_url: !!python/unicode 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_peptideshaker_0_39'
name: !!python/unicode 'package_peptideshaker_0_39'
owner: !!python/unicode 'iracooke'
