categories: !!python/tuple [Tool Dependency Packages]
description: !!python/unicode 'Tool dependencies for Morpheus 255'
homepage_url: !!python/unicode 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_morpheus_255'
name: !!python/unicode 'package_morpheus_255'
owner: !!python/unicode 'galaxyp'
