categories:
- Proteomics
description: GCC2016 Tutorial Workflows
long_description: |
  Workflows for PeptideShaker and NOVEL peptides analysis

Typical workflow:  
name: gcc2016_tutorial
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/workflows/gcc2016_tutorial
type: unrestricted
