categories:
- Proteomics
description: Map peptides to a reference genome
long_description: |
  Map peptides to a reference genome using a bed file the locates the proein sequence in the
  reference genome.  This is intended for use with the bed output of the 
  translate_bed_sequences tool.   

name: map_peptides_to_bed
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/map_peptides_to_bed
type: unrestricted
