categories:
- Tool Dependency Packages
- Proteomics
name: package_tokyocabinet_1_4_48
description: Contains TokyoCabinet tool dependency definition that downloads and builds TokyoCabinet
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/packages/package_tokyocabinet_1_4_48/
type: tool_dependency_definition
owner: galaxyp
