categories: !!python/tuple [Tool Dependency Packages]
description: !!python/unicode 'Tool dependencies for mz_to_sqlite 1.0'
homepage_url: !!python/unicode 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_mztosqlite_1_0_0'
name: !!python/unicode 'package_mztosqlite_1_0_0'
owner: !!python/unicode 'galaxyp'
