owner: galaxyp
name: sixgill
categories:
- Proteomics
- MetaProteomics
description: Six-frame Genome-Inferred Libraries for LC-MS/MS
long_description: |
  Sixgill (Six-frame Genome-Inferred Libraries for LC-MS/MS) is a tool 
  for using shotgun metagenomics sequencing reads to construct databases 
  of 'metapeptides': short protein fragments for database search i
  of LC-MS/MS metaproteomics data.

  https://github.com/dhmay/sixgill
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/sixgill
type: unrestricted
